mashin = []
mashin.append('Рома')
mashin.append('Илья')
mashin.append('Артем')
mashin.append('Юля')
mashin.append('Артем')
mashin.append('Ярослав')
mashin.append('Стас')
mashin.append('Илья')
mashin.append('Леша')
print(mashin)
